### ISSUE TITLE
Buttery-eel as basecaller

### ISSUE THREAD

**Issue by Psy-Fer** [Tomcxf/FASTdRNA#1]
Hey there,

I noticed you convert your fast5 files to slow5, then basecall the fast5 files with guppy

If you want to just work with slow5, you can use `buttery-eel` which is a wrapper for guppy but lets you basecall slow5 files

https://github.com/Psy-Fer/buttery-eel

Anyway, cool workflow!
Cheers,
James

**Comment by Tomcxf** [comment]
Thanks for your recommendation!
Buttery-eel is an amazing tool to solve Slow5 basecalling, thanks for your donation!
By the way, I just wonder if it can handle direct RNA data, because the example you offer is DNA data.
Thank!
Best wishes,
Chen

**Comment by Psy-Fer** [comment]
Hey Chen,

Yes it can do RNA as well.

There was some issue with T/U that Hiruna raised the other day that i need to look into, but not sure if that is guppy being weird or butter-eel. But I'll get to that next week sometime.

In the mean time, it's pretty quick to test it on your data.
If you have any troubles, just let me know :) 

Cheers,
James

**Comment by Tomcxf** [comment]
Dear Dr. James,
Thanks for your suggestion!
I will try your software as soon as possible.
Thanks for your warmhearted help!
Best wishes,
Chen
