### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by MarioRinBarr** [Tomcxf/FASTdRNA#5]
Hi,

I am interested in using your programme, but I am not able to get it to work. When running it always gives me a syntax error in the script, which I have not modified:

snakemake -s dRNAmain.py -c 4 --set-threads myrule=32
SyntaxError in file /media/mario/88568EEF568EDCF6/FASTdRNA/dRNAmain.py, line 23:
Colon expected after keyword shell. (dRNAmain.py, line 23)

On the other hand, I don't know if it's because I'm putting the command line wrong. I can't find detailed documentation on how each script should run.

Thank you very much,
Mario

**Comment by Tomcxf** [comment]
Hi !
I felt so sorry that mistaken colon type since last time modification.
I have corrected it and you can test whether it work !
By the way, the detailed document for use is under constructed, so if you want to read, you can read the origin paper I linked in HomePage!
Thanks for your feedback :)
